// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Suits",
    url: "https://m.media-amazon.com/images/I/71HGgigujnL._SL1500_.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Narcos",
    url: "https://flxt.tmsimg.com/assets/p11993088_b1t_v8_aa.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Lucifer",
    url: "https://i.pinimg.com/originals/95/92/ad/9592ad6e018406ecffd67b15c044ed94.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Dirilis Ertugrul",
    url: "https://i.tribune.com.pk/media/images/2223884-dirilis_ertugrul_ver_xlg-1589788075/2223884-dirilis_ertugrul_ver_xlg-1589788075.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The Walking Dead",
    url: "https://flxt.tmsimg.com/assets/p8282918_b_v13_bf.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Peaky Blinders",
    url: "https://m.media-amazon.com/images/M/MV5BMTkzNjEzMDEzMF5BMl5BanBnXkFtZTgwMDI0MjE4MjE@._V1_FMjpg_UX1000_.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "The Good Doctor",
    url: "https://flxt.tmsimg.com/assets/p17114293_b_v13_ac.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Squid Game",
    url: "https://www.filmpolicereviews.com/wp-content/uploads/2021/09/ENUS_SQdGame_Main_Playground_Vertical_27x40_RGB_PRE-1170x1733.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "The Queen's Gambit",
    url: "https://m.media-amazon.com/images/M/MV5BM2EwMmRhMmUtMzBmMS00ZDQ3LTg4OGEtNjlkODk3ZTMxMmJlXkEyXkFqcGdeQXVyMjM5ODk1NDU@._V1_.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Cobra Kai",
    url: "https://m.media-amazon.com/images/M/MV5BOTE1M2Q3YjQtZGMzYy00MDcwLWIzNzctYzI3MDBhMjBmYTQwXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "House of Cards",
    url: "https://3.bp.blogspot.com/-AIAC7yyt2aI/WV5Yv_Tax5I/AAAAAAAABxw/cSNIqeiesSIR-NWhv3x_3zK2VG1v9dECACLcBGAs/s1600/netflix_hoc_mobile.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "Money Heist",
    url: "https://m.media-amazon.com/images/M/MV5BNDJkYzY3MzMtMGFhYi00MmQ4LWJkNTgtZGNiZWZmMTMxNzdlXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
];